No setup_requires of distribute
distribute was long ago merged into setuptools and distribute is no
longer maintained.

```
CORP\marca@tcagent109:~/5af33023674b0583$ .tox/py34/bin/pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2680, in _dep_map
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2525, in __getattr__
    AttributeError: _DistInfoDistribution__dep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 243, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 273, in run
        return func()
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 242, in runner
        _execfile(setup_script, ns)
      File "/home/teamcity/work/5af33023674b0583/.tox/py34/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/setup.py", line 58, in <module>
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/setuptools/command/bdist_egg.py", line 177, in run
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/setuptools/command/egg_info.py", line 177, in run
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2241, in load
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2254, in require
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2471, in requires
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2682, in _dep_map
      File "/tmp/easy_install-b5nt6gsu/distribute-0.7.3/pkg_resources.py", line 2699, in _compute_dependencies
    ImportError: No module named '_markerlib'
```